const fs = require('fs');
const files = {
  'projects.ts': "import { apiClient } from './client';\n\nexport interface Project { id: string; name: string; }\n\nexport const getProjects = () => apiClient<Project[]>('/projects');\nexport const getProject = (id: string) => apiClient<Project>(`/projects/${id}`);\nexport const createProject = (data: Partial<Project>) => apiClient<Project>('/projects', { method: 'POST', body: JSON.stringify(data) });",
  'sources.ts': "import { apiClient } from './client';\n\nexport interface Source { id: string; filename: string; content: string; }\n\nexport const getSources = (projectId: string) => apiClient<Source[]>(`/projects/${projectId}/sources`);\nexport const createSource = (projectId: string, data: Partial<Source>) => apiClient<Source>(`/projects/${projectId}/sources`, { method: 'POST', body: JSON.stringify(data) });",
  'analysis.ts': "import { apiClient } from './client';\n\nexport interface AnalysisResult { id: string; functions: any[]; }\n\nexport const analyzeProject = (projectId: string) => apiClient<AnalysisResult>(`/projects/${projectId}/analyze`, { method: 'POST' });\nexport const getAnalysis = (projectId: string) => apiClient<AnalysisResult>(`/projects/${projectId}/analysis`);",
  'scope.ts': "import { apiClient } from './client';\n\nexport interface Scope { id: string; selectedFunctions: string[]; }\n\nexport const getScope = (projectId: string) => apiClient<Scope>(`/projects/${projectId}/scope`);\nexport const updateScope = (projectId: string, data: Scope) => apiClient<Scope>(`/projects/${projectId}/scope`, { method: 'PUT', body: JSON.stringify(data) });",
  'dependencies.ts': "import { apiClient } from './client';\n\nexport interface Dependency { id: string; name: string; }\n\nexport const getDependencies = (projectId: string) => apiClient<Dependency[]>(`/projects/${projectId}/dependencies`);\nexport const createDependency = (projectId: string, data: Partial<Dependency>) => apiClient<Dependency>(`/projects/${projectId}/dependencies`, { method: 'POST', body: JSON.stringify(data) });",
  'stubs.ts': "import { apiClient } from './client';\n\nexport interface Stub { id: string; functionName: string; logic: string; }\n\nexport const getStubs = (projectId: string) => apiClient<Stub[]>(`/projects/${projectId}/stubs`);\nexport const createStub = (projectId: string, data: Partial<Stub>) => apiClient<Stub>(`/projects/${projectId}/stubs`, { method: 'POST', body: JSON.stringify(data) });",
  'tests.ts': "import { apiClient } from './client';\n\nexport interface TestSuite { id: string; name: string; }\nexport interface TestCase { id: string; suiteId: string; vector: any; }\n\nexport const getTestSuites = (projectId: string) => apiClient<TestSuite[]>(`/projects/${projectId}/test-suites`);\nexport const createTestSuite = (projectId: string, data: Partial<TestSuite>) => apiClient<TestSuite>(`/projects/${projectId}/test-suites`, { method: 'POST', body: JSON.stringify(data) });\nexport const getTestCases = (projectId: string) => apiClient<TestCase[]>(`/projects/${projectId}/test-cases`);\nexport const createTestCase = (projectId: string, data: Partial<TestCase>) => apiClient<TestCase>(`/projects/${projectId}/test-cases`, { method: 'POST', body: JSON.stringify(data) });",
  'executions.ts': "import { apiClient } from './client';\n\nexport interface Execution { id: string; status: 'QUEUED' | 'BUILDING' | 'RUNNING' | 'PASS' | 'FAIL' | 'ERROR' | 'CANCELLED'; }\n\nexport const createExecution = (projectId: string, payload: any) => apiClient<Execution>(`/projects/${projectId}/executions`, { method: 'POST', body: JSON.stringify(payload) });\nexport const getExecution = (projectId: string, id: string) => apiClient<Execution>(`/projects/${projectId}/executions/${id}`);",
  'coverage.ts': "import { apiClient } from './client';\n\nexport interface Coverage { statement: number; decision: number; }\n\nexport const getCoverage = (projectId: string, executionId: string) => apiClient<Coverage>(`/projects/${projectId}/executions/${executionId}/coverage`);",
  'mcdc.ts': "import { apiClient } from './client';\n\nexport interface MCDC { conditions: { id: string; description: string; evaluated: boolean }[]; gapAdvisor?: { suggestedVector: any } }\n\nexport const getMcdc = (projectId: string, executionId: string) => apiClient<MCDC>(`/projects/${projectId}/executions/${executionId}/mcdc`);",
  'traceability.ts': "import { apiClient } from './client';\n\nexport interface Traceability { links: { reqId: string; description: string }[]; }\n\nexport const getTraceability = (projectId: string) => apiClient<Traceability>(`/projects/${projectId}/traceability`);",
  'evidence.ts': "import { apiClient } from './client';\n\nexport interface Evidence { freshness: 'CURRENT' | 'STALE' | 'INVALIDATED'; generatedAt: string; }\n\nexport const getEvidence = (projectId: string) => apiClient<Evidence>(`/projects/${projectId}/evidence`);\nexport const exportEvidence = (projectId: string) => apiClient<any>(`/projects/${projectId}/evidence/export`);"
};

for (const [name, content] of Object.entries(files)) {
  fs.writeFileSync('src/api/' + name, content);
}
