import json
import hashlib
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field

from apps.api.app.domain.enums import EvidenceFreshness, ExecutionStatus


class EvidenceReport(BaseModel):
    evidence_id: str
    project_id: str
    execution_id: str
    tool_version: str = "HonAero Sentinel Verification Studio v1.0.0"
    created_at: str
    freshness: EvidenceFreshness = EvidenceFreshness.CURRENT
    source_checksum: str
    stub_checksum: Optional[str] = None
    vector_checksum: Optional[str] = None
    target_function: str
    requirement_ids: List[str] = Field(default_factory=list)
    source_files: List[str] = Field(default_factory=list)
    compiler: Dict[str, Any] = Field(default_factory=dict)
    stubs: List[Dict[str, Any]] = Field(default_factory=list)
    test_vectors: List[Dict[str, Any]] = Field(default_factory=list)
    execution_status: ExecutionStatus
    duration_ms: float = 0.0
    stdout: str = ""
    stderr: str = ""
    coverage: Dict[str, Any] = Field(default_factory=dict)
    mcdc: Dict[str, Any] = Field(default_factory=dict)
    disclaimer: str = (
        "Evidence record generated by HonAero Sentinel verification platform. "
        "Reviewable compliance artifact subject to systems engineering sign-off."
    )


class EvidenceService:
    """
    Creates immutable evidence records, computes cryptographic checksums,
    and calculates current vs stale verification freshness states.
    """

    @staticmethod
    def compute_source_checksum(sources: Dict[str, str]) -> str:
        hasher = hashlib.sha256()
        for fname in sorted(sources.keys()):
            hasher.update(fname.encode("utf-8"))
            hasher.update(sources[fname].encode("utf-8"))
        return hasher.hexdigest()

    @staticmethod
    def compute_config_checksum(data: Any) -> str:
        serialized = json.dumps(data, sort_keys=True)
        return hashlib.sha256(serialized.encode("utf-8")).hexdigest()

    @staticmethod
    def evaluate_freshness(
        current_source_hash: str,
        evidence_source_hash: str,
        current_stub_hash: Optional[str] = None,
        evidence_stub_hash: Optional[str] = None,
    ) -> EvidenceFreshness:
        if current_source_hash != evidence_source_hash:
            return EvidenceFreshness.STALE
        if current_stub_hash and evidence_stub_hash and (current_stub_hash != evidence_stub_hash):
            return EvidenceFreshness.STALE
        return EvidenceFreshness.CURRENT

    def build_evidence_record(
        self,
        evidence_id: str,
        project_id: str,
        execution_id: str,
        target_function: str,
        requirement_ids: List[str],
        source_files: Dict[str, str],
        stubs: List[Dict[str, Any]],
        vectors: List[Dict[str, Any]],
        compiler_info: Dict[str, Any],
        execution_status: ExecutionStatus,
        duration_ms: float,
        stdout: str,
        stderr: str,
        coverage_data: Dict[str, Any],
        mcdc_data: Dict[str, Any],
    ) -> EvidenceReport:
        src_hash = self.compute_source_checksum(source_files)
        stub_hash = self.compute_config_checksum(stubs) if stubs else None
        vec_hash = self.compute_config_checksum(vectors) if vectors else None

        return EvidenceReport(
            evidence_id=evidence_id,
            project_id=project_id,
            execution_id=execution_id,
            created_at=datetime.now(timezone.utc).isoformat(),
            freshness=EvidenceFreshness.CURRENT,
            source_checksum=src_hash,
            stub_checksum=stub_hash,
            vector_checksum=vec_hash,
            target_function=target_function,
            requirement_ids=requirement_ids,
            source_files=sorted(list(source_files.keys())),
            compiler=compiler_info,
            stubs=stubs,
            test_vectors=vectors,
            execution_status=execution_status,
            duration_ms=duration_ms,
            stdout=stdout,
            stderr=stderr,
            coverage=coverage_data,
            mcdc=mcdc_data,
        )

    def export_json(self, report: EvidenceReport) -> str:
        return report.model_dump_json(indent=2)

    def export_markdown_or_text(self, report: EvidenceReport, out_path: Path) -> Path:
        """Generates a human-reviewable compliance summary report."""
        out_path.parent.mkdir(parents=True, exist_ok=True)
        content = [
            "# HonAero Sentinel — Software Verification Evidence Record",
            "",
            f"**Evidence ID:** {report.evidence_id}  ",
            f"**Execution ID:** {report.execution_id}  ",
            f"**Project ID:** {report.project_id}  ",
            f"**Target Function:** `{report.target_function}`  ",
            f"**Timestamp:** {report.created_at}  ",
            f"**Freshness Status:** `{report.freshness.value}`  ",
            f"**Source Checksum (SHA-256):** `{report.source_checksum}`  ",
            "",
            "## 1. Traceability",
            f"- **Linked Requirements:** {', '.join(report.requirement_ids) or 'None'}",
            f"- **Source Files:** {', '.join(report.source_files)}",
            "",
            "## 2. Compiler & Execution",
            f"- **Compiler:** {report.compiler.get('name', 'gcc')} ({report.compiler.get('version', 'unknown')})",
            f"- **Compiler Flags:** `{report.compiler.get('flags', '')}`",
            f"- **Execution Status:** **{report.execution_status.value}**",
            f"- **Execution Duration:** {report.duration_ms:.2f} ms",
            "",
            "## 3. Coverage Analysis",
            f"- **Statement Coverage:** {report.coverage.get('statement_coverage_pct', 0.0)}%",
            f"- **Branch Coverage:** {report.coverage.get('branch_coverage_pct', 0.0)}%",
            f"- **Line Coverage:** {report.coverage.get('line_coverage_pct', 0.0)}%",
            "",
            "## 4. MC/DC Analysis",
            f"- **MC/DC Percentage:** {report.mcdc.get('coverage_percentage', 0.0)}%",
            f"- **Total Conditions:** {report.mcdc.get('total_conditions', 0)}",
            f"- **Proven Conditions:** {report.mcdc.get('proven_conditions', 0)}",
            "",
            "## 5. Reviewer Sign-off & Disclaimer",
            report.disclaimer,
            "",
        ]
        out_path.write_text("\n".join(content), encoding="utf-8")
        return out_path

