#include "sentinel/harness/harness_generator.hpp"
#include "sentinel/common/sha256.hpp"
#include <fstream>
#include <sstream>
#include <filesystem>
#include <iomanip>

namespace sentinel {

namespace fs = std::filesystem;

std::string HarnessGenerator::generateStubsHeader(
    const std::vector<StubConfiguration>& stubs,
    const std::string& targetHeader)
{
    std::ostringstream oss;
    oss << "/* ============================================================\n";
    oss << " * HONAERO SENTINEL — DETERMINISTIC STUBS HEADER\n";
    oss << " * Generated by Sentinel Verification Core SDK\n";
    oss << " * ============================================================ */\n\n";
    oss << "#ifndef SENTINEL_GENERATED_STUBS_H\n";
    oss << "#define SENTINEL_GENERATED_STUBS_H\n\n";
    oss << "#include <stdint.h>\n";
    oss << "#include <stdbool.h>\n\n";

    if (!targetHeader.empty()) {
        oss << "#include \"" << fs::path(targetHeader).filename().string() << "\"\n\n";
    }

    oss << "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n";
    oss << "/* Stub Reset and State Inspection API */\n";
    oss << "void sentinel_reset_stubs(void);\n\n";

    for (const auto& s : stubs) {
        if (s.mode == "STUB") {
            oss << "/* Stub: " << s.function_name << " */\n";
            oss << "extern int sentinel_" << s.function_name << "_call_count;\n";
            // Prototype declaration if not in header
            oss << s.return_type << " " << s.function_name << "(";
            if (s.function_name == "sensor_read") {
                oss << "void";
            } else if (s.function_name == "valve_actuate") {
                oss << "int position_pct";
            } else {
                oss << "void";
            }
            oss << ");\n\n";
        }
    }

    oss << "#ifdef __cplusplus\n}\n#endif\n\n";
    oss << "#endif /* SENTINEL_GENERATED_STUBS_H */\n";
    return oss.str();
}

std::string HarnessGenerator::generateStubsSource(const std::vector<StubConfiguration>& stubs) {
    std::ostringstream oss;
    oss << "/* ============================================================\n";
    oss << " * HONAERO SENTINEL — DETERMINISTIC STUBS IMPLEMENTATION\n";
    oss << " * ============================================================ */\n\n";
    oss << "#include \"stubs.h\"\n";
    oss << "#include <stdio.h>\n\n";

    for (const auto& s : stubs) {
        if (s.mode == "STUB") {
            oss << "/* Stub state for: " << s.function_name << " */\n";
            oss << "int sentinel_" << s.function_name << "_call_count = 0;\n";
            
            // Successive returns array
            if (!s.return_values.empty() && s.return_type != "void") {
                oss << "static const " << s.return_type << " sentinel_" << s.function_name << "_sequence[] = {";
                for (size_t i = 0; i < s.return_values.size(); ++i) {
                    if (i > 0) oss << ", ";
                    if (s.return_values[i].is_number_integer()) {
                        oss << s.return_values[i].get<int>();
                    } else if (s.return_values[i].is_number_float()) {
                        oss << s.return_values[i].get<double>();
                    } else if (s.return_values[i].is_boolean()) {
                        oss << (s.return_values[i].get<bool>() ? "1" : "0");
                    } else {
                        oss << "0";
                    }
                }
                oss << "};\n";
                oss << "static const int sentinel_" << s.function_name << "_sequence_len = " << s.return_values.size() << ";\n\n";
            }

            // Function definition
            oss << s.return_type << " " << s.function_name << "(";
            if (s.function_name == "sensor_read") {
                oss << "void";
            } else if (s.function_name == "valve_actuate") {
                oss << "int position_pct";
            } else {
                oss << "void";
            }
            oss << ") {\n";
            oss << "    int call_idx = sentinel_" << s.function_name << "_call_count++;\n";

            if (!s.custom_c_body.empty()) {
                oss << "    " << s.custom_c_body << "\n";
            } else if (s.return_type == "void") {
                oss << "    /* void stub */\n";
            } else if (!s.return_values.empty()) {
                oss << "    if (call_idx < sentinel_" << s.function_name << "_sequence_len) {\n";
                oss << "        return sentinel_" << s.function_name << "_sequence[call_idx];\n";
                oss << "    }\n";
                oss << "    return sentinel_" << s.function_name << "_sequence[sentinel_" << s.function_name << "_sequence_len - 1];\n";
            } else {
                oss << "    return 0;\n";
            }
            oss << "}\n\n";
        }
    }

    oss << "void sentinel_reset_stubs(void) {\n";
    for (const auto& s : stubs) {
        if (s.mode == "STUB") {
            oss << "    sentinel_" << s.function_name << "_call_count = 0;\n";
        }
    }
    oss << "}\n";

    return oss.str();
}

std::string HarnessGenerator::generateTestVectorsSource(
    const std::vector<TestVector>& vectors,
    const FunctionInfo& targetFunction)
{
    std::ostringstream oss;
    oss << "/* ============================================================\n";
    oss << " * HONAERO SENTINEL — TEST VECTORS DEFINITION\n";
    oss << " * ============================================================ */\n\n";
    oss << "#include <stdint.h>\n";
    oss << "#include <stdbool.h>\n\n";

    oss << "typedef struct {\n";
    oss << "    int vector_index;\n";
    oss << "    const char* description;\n";
    for (const auto& param : targetFunction.parameters) {
        oss << "    " << param.type << " " << param.name << ";\n";
    }
    oss << "    " << targetFunction.return_type << " expected_return;\n";
    oss << "} SentinelTestCaseRecord;\n\n";

    oss << "static const SentinelTestCaseRecord SENTINEL_TEST_VECTORS[] = {\n";
    for (size_t i = 0; i < vectors.size(); ++i) {
        const auto& v = vectors[i];
        oss << "    {\n";
        oss << "        " << v.vector_index << ",\n";
        oss << "        \"" << (v.description.empty() ? "Test Vector " + std::to_string(v.vector_index) : v.description) << "\",\n";
        for (const auto& param : targetFunction.parameters) {
            oss << "        ";
            auto it = v.inputs.find(param.name);
            if (it != v.inputs.end()) {
                if (it->second.is_number_integer()) oss << it->second.get<int>();
                else if (it->second.is_number_float()) oss << it->second.get<double>();
                else if (it->second.is_boolean()) oss << (it->second.get<bool>() ? "1" : "0");
                else oss << "0";
            } else {
                oss << "0";
            }
            oss << ", /* " << param.name << " */\n";
        }
        oss << "        ";
        auto retIt = v.expected_outputs.find("return");
        if (retIt != v.expected_outputs.end()) {
            if (retIt->second.is_number_integer()) oss << retIt->second.get<int>();
            else if (retIt->second.is_number_float()) oss << retIt->second.get<double>();
            else if (retIt->second.is_boolean()) oss << (retIt->second.get<bool>() ? "1" : "0");
            else oss << "0";
        } else {
            oss << "0";
        }
        oss << "  /* expected_return */\n";
        oss << "    }" << (i + 1 < vectors.size() ? "," : "") << "\n";
    }
    oss << "};\n\n";
    oss << "static const int SENTINEL_NUM_TEST_VECTORS = " << vectors.size() << ";\n";
    return oss.str();
}

std::string HarnessGenerator::generateMainHarness(const HarnessRequest& request) {
    std::ostringstream oss;
    oss << "/* ============================================================\n";
    oss << " * HONAERO SENTINEL — AUTOMATED TEST HARNESS MAIN\n";
    oss << " * Target: " << request.target_function.name << "\n";
    oss << " * ============================================================ */\n\n";
    oss << "#include <stdio.h>\n";
    oss << "#include <stdlib.h>\n";
    oss << "#include <string.h>\n";
    oss << "#include <stdbool.h>\n";
    oss << "#include \"stubs.h\"\n\n";

    if (!request.target_header_file.empty()) {
        oss << "#include \"" << fs::path(request.target_header_file).filename().string() << "\"\n\n";
    } else {
        // Direct prototype
        oss << request.target_function.return_type << " " << request.target_function.name << "(";
        for (size_t i = 0; i < request.target_function.parameters.size(); ++i) {
            if (i > 0) oss << ", ";
            oss << request.target_function.parameters[i].type << " " << request.target_function.parameters[i].name;
        }
        oss << ");\n\n";
    }

    oss << "/* Include generated vectors */\n";
    oss << "#include \"test_vectors.cpp\"\n\n";

    oss << "int main(int argc, char** argv) {\n";
    oss << "    (void)argc; (void)argv;\n";
    oss << "    int total_passed = 0;\n";
    oss << "    int total_failed = 0;\n\n";

    oss << "    /* 1. Setup hook */\n";
    if (!request.hooks.setup_code.empty()) {
        oss << "    " << request.hooks.setup_code << "\n";
    }

    oss << "    printf(\"{\\n\");\n";
    oss << "    printf(\"  \\\"execution_id\\\": \\\"sentinel_exec_local\\\",\\n\");\n";
    oss << "    printf(\"  \\\"target_function\\\": \\\"" << request.target_function.name << "\\\",\\n\");\n";
    oss << "    printf(\"  \\\"test_results\\\": [\\n\");\n\n";

    oss << "    for (int i = 0; i < SENTINEL_NUM_TEST_VECTORS; ++i) {\n";
    oss << "        const SentinelTestCaseRecord* tc = &SENTINEL_TEST_VECTORS[i];\n\n";

    oss << "        /* 2. Configure stubs */\n";
    oss << "        sentinel_reset_stubs();\n\n";

    oss << "        /* 3. Before-test hook */\n";
    if (!request.hooks.before_test_code.empty()) {
        oss << "        " << request.hooks.before_test_code << "\n";
    }

    oss << "        /* 4. Call target function & 5. Capture output */\n";
    oss << "        " << request.target_function.return_type << " actual = " << request.target_function.name << "(";
    for (size_t p = 0; p < request.target_function.parameters.size(); ++p) {
        if (p > 0) oss << ", ";
        oss << "tc->" << request.target_function.parameters[p].name;
    }
    oss << ");\n\n";

    oss << "        /* 6. Compare output */\n";
    oss << "        bool passed = (actual == tc->expected_return);\n";
    oss << "        if (passed) total_passed++; else total_failed++;\n\n";

    oss << "        /* 7. Record result */\n";
    oss << "        printf(\"    {\\n\");\n";
    oss << "        printf(\"      \\\"vector_index\\\": %d,\\n\", tc->vector_index);\n";
    oss << "        printf(\"      \\\"status\\\": \\\"%s\\\",\\n\", passed ? \"PASSED\" : \"FAILED\");\n";
    oss << "        printf(\"      \\\"actual_return\\\": %d,\\n\", (int)actual);\n";
    oss << "        printf(\"      \\\"expected_return\\\": %d\\n\", (int)tc->expected_return);\n";
    oss << "        printf(\"    }%s\\n\", (i + 1 < SENTINEL_NUM_TEST_VECTORS) ? \",\" : \"\");\n\n";

    oss << "        /* 8. After-test hook */\n";
    if (!request.hooks.after_test_code.empty()) {
        oss << "        " << request.hooks.after_test_code << "\n";
    }
    oss << "    }\n\n";

    oss << "    /* 9. Teardown hook */\n";
    if (!request.hooks.teardown_code.empty()) {
        oss << "    " << request.hooks.teardown_code << "\n";
    }

    oss << "    /* 10. Emit machine-readable result */\n";
    oss << "    printf(\"  ],\\n\");\n";
    oss << "    printf(\"  \\\"summary\\\": {\\n\");\n";
    oss << "    printf(\"    \\\"total\\\": %d,\\n\", SENTINEL_NUM_TEST_VECTORS);\n";
    oss << "    printf(\"    \\\"passed\\\": %d,\\n\", total_passed);\n";
    oss << "    printf(\"    \\\"failed\\\": %d,\\n\", total_failed);\n";
    oss << "    printf(\"    \\\"status\\\": \\\"%s\\\"\\n\", (total_failed == 0) ? \"PASSED\" : \"FAILED\");\n";
    oss << "    printf(\"  }\\n\");\n";
    oss << "    printf(\"}\\n\");\n\n";
    oss << "    return (total_failed == 0) ? 0 : 1;\n";
    oss << "}\n";

    return oss.str();
}

HarnessResult HarnessGenerator::generate(const HarnessRequest& request) {
    HarnessResult result;
    try {
        fs::path outDir = request.output_directory.empty() ? fs::current_path() / "generated" : fs::path(request.output_directory);
        fs::create_directories(outDir);

        fs::path stubsHeaderPath = outDir / "stubs.h";
        fs::path stubsSrcPath = outDir / "stubs.cpp";
        fs::path vectorsSrcPath = outDir / "test_vectors.cpp";
        fs::path harnessSrcPath = outDir / "harness.cpp";

        std::string stubsHeader = generateStubsHeader(request.stubs, request.target_header_file);
        std::string stubsSrc = generateStubsSource(request.stubs);
        std::string vectorsSrc = generateTestVectorsSource(request.test_vectors, request.target_function);
        std::string harnessSrc = generateMainHarness(request);

        std::ofstream(stubsHeaderPath) << stubsHeader;
        std::ofstream(stubsSrcPath) << stubsSrc;
        std::ofstream(vectorsSrcPath) << vectorsSrc;
        std::ofstream(harnessSrcPath) << harnessSrc;

        result.success = true;
        result.stubs_header_file = stubsHeaderPath.string();
        result.stubs_source_file = stubsSrcPath.string();
        result.test_vectors_source_file = vectorsSrcPath.string();
        result.harness_source_file = harnessSrcPath.string();

        // Calculate combined hash of generated artifacts
        std::string combined = stubsHeader + stubsSrc + vectorsSrc + harnessSrc;
        result.generated_code_hash = Sha256::hashString(combined);

    } catch (const std::exception& e) {
        result.success = false;
        result.error_message = e.what();
    }
    return result;
}

} // namespace sentinel
