from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
import uuid
from datetime import datetime, timezone
from enum import Enum


class ProvenanceType(str, Enum):
    EXPLICIT_REQUIREMENT = "EXPLICIT_REQUIREMENT"
    DERIVED_FROM_SOURCE = "DERIVED_FROM_SOURCE"
    TESTER_CONSTRAINT = "TESTER_CONSTRAINT"
    AI_INFERRED = "AI_INFERRED"


class ProposalReviewStatus(str, Enum):
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EDITED = "EDITED"


class AIModelDTO(BaseModel):
    id: str
    name: str
    provider: str = "NVIDIA_NIM"
    available: bool = False
    contextWindow: int = 4096
    description: str = ""


class AIProviderStatusDTO(BaseModel):
    provider: str = "NVIDIA_NIM"
    isConfigured: bool = False
    baseUrl: str = "https://integrate.api.nvidia.com/v1"
    activeModel: str = "meta/llama-3.3-70b-instruct"
    currentModel: str = "meta/llama-3.3-70b-instruct"
    liveCallTested: bool = False
    do178cNotice: str = "DO-178C Advisory Notice: All AI-generated outputs are advisory proposals. Authoritative verdicts are generated by deterministic verification engine."
    details: Dict[str, Any] = Field(default_factory=dict)


# --- Requirements Extraction ---
class AIRequirementProposal(BaseModel):
    proposalId: str = Field(default_factory=lambda: str(uuid.uuid4()))
    identifier: str  # e.g. HLR-AI-001
    title: str
    description: str
    section: Optional[str] = None
    parameters: List[str] = Field(default_factory=list)
    constraints: List[str] = Field(default_factory=list)
    preconditions: Dict[str, Any] = Field(default_factory=dict)
    postconditions: Dict[str, Any] = Field(default_factory=dict)
    expectedBehavior: str = ""
    boundaryConditions: List[str] = Field(default_factory=list)
    provenance: ProvenanceType = ProvenanceType.AI_INFERRED
    uncertainties: List[str] = Field(default_factory=list)
    status: ProposalReviewStatus = ProposalReviewStatus.PROPOSED


class AIReqExtractRequest(BaseModel):
    document: Optional[str] = None
    spec_text: Optional[str] = None
    sourceId: Optional[str] = None
    documentId: Optional[str] = None


class AIApproveRequirementRequest(BaseModel):
    proposalId: Optional[str] = None
    identifier: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None
    section: Optional[str] = None
    acceptanceCriteria: Optional[str] = None
    proposal: Optional[Dict[str, Any]] = None
    reviewed_by: Optional[str] = None


# --- Test Case Proposals ---
class AITestCaseProposal(BaseModel):
    proposalId: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    targetFunctionId: Optional[str] = None
    targetFunctionName: str = ""
    category: str = "NORMAL"  # NORMAL, BOUNDARY, INVALID_INPUT, REQUIREMENT_BASED, FAULT_INJECTION, SCENARIO
    inputs: Dict[str, Any] = Field(default_factory=dict)
    expectedOutputs: Dict[str, Any] = Field(default_factory=dict)
    hasApprovedOracle: bool = True
    rationale: str = ""
    requirementIds: List[str] = Field(default_factory=list)
    suggestedAssertions: List[Dict[str, Any]] = Field(default_factory=list)
    uncertainties: List[str] = Field(default_factory=list)
    provenance: ProvenanceType = ProvenanceType.AI_INFERRED
    status: ProposalReviewStatus = ProposalReviewStatus.PROPOSED


class AIGenerateTestsRequest(BaseModel):
    functionId: Optional[str] = None
    target_function: Optional[str] = None
    category: Optional[str] = "ALL"  # ALL, NORMAL, BOUNDARY, INVALID_INPUT, FAULT_INJECTION, SCENARIO
    requirementId: Optional[str] = None


class AIApproveTestProposalRequest(BaseModel):
    proposalId: Optional[str] = None
    testSuiteId: Optional[str] = None
    targetFunctionId: Optional[str] = None
    name: Optional[str] = None
    inputs: Optional[Dict[str, Any]] = None
    expectedOutputs: Optional[Dict[str, Any]] = None
    proposal: Optional[Dict[str, Any]] = None
    reviewed_by: Optional[str] = None


# --- Scenario Generation ---
class AIScenarioStep(BaseModel):
    stepIndex: int
    flightPhase: str  # PREFLIGHT, TAKEOFF_CLIMB, CRUISE, DESCENT, APPROACH_LANDING, TRANSITION
    inputs: Dict[str, Any]
    expectedState: str
    durationSeconds: float = 1.0


class AIScenarioSequenceProposal(BaseModel):
    proposalId: str = Field(default_factory=lambda: str(uuid.uuid4()))
    scenarioName: str
    targetFunction: str
    flightPhase: str
    steps: List[AIScenarioStep]
    rationale: str
    status: ProposalReviewStatus = ProposalReviewStatus.PROPOSED


class AIScenarioRequest(BaseModel):
    functionId: Optional[str] = None
    flightPhase: Optional[str] = "ALL"
    scenario_type: Optional[str] = None


# --- Fault Injection ---
class AIFaultInjectionProposal(BaseModel):
    proposalId: str = Field(default_factory=lambda: str(uuid.uuid4()))
    targetFunction: str
    faultType: str  # SENSOR_SPIKE, STUCK_VALUE, NOISE, DRIFT, STALE_DATA, MISSING_DATA, INVALID_RANGE
    targetParameter: str
    faultParameters: Dict[str, Any]
    rationale: str
    impactAnalysis: str
    status: ProposalReviewStatus = ProposalReviewStatus.PROPOSED


class AIFaultSuggestRequest(BaseModel):
    functionId: Optional[str] = None
    fault_type: Optional[str] = None


# --- Failure Explanation ---
class AIFailureExplanation(BaseModel):
    executionId: str
    verdict: str
    observedEvidence: Dict[str, Any]
    possibleCauses: List[str]
    suggestedRemediation: List[str]
    confidenceScore: float = 0.95
    supportingLogReferences: List[str] = Field(default_factory=list)


class AIExplainRequest(BaseModel):
    executionId: Optional[str] = None
    run_id: Optional[str] = None
    failure_logs: Optional[str] = None


# --- Coverage Gap Recommendation ---
class AICoverageGapRecommendation(BaseModel):
    gapId: str = Field(default_factory=lambda: str(uuid.uuid4()))
    decisionId: str
    conditionId: Optional[str] = None
    sourceLocation: str
    uncoveredOutcome: str  # TRUE or FALSE
    gapDescription: str
    proposedVector: Dict[str, Any]
    targetedBranch: str
    rationale: str
    uncertainty: str = ""


# --- Adaptive Retesting ---
class AIAdaptiveRetestProposal(BaseModel):
    originalExecutionId: str
    investigationGoal: str
    diagnosticTestProposals: List[AITestCaseProposal]
    rationale: str


class AIAdaptiveRetestRequest(BaseModel):
    executionId: Optional[str] = None
    failed_run_id: Optional[str] = None


# --- Test Suite Optimization ---
class AITestSuiteOptimization(BaseModel):
    totalTestsBefore: int
    recommendedTestsAfter: int
    redundantTestIds: List[str]
    essentialTestIds: List[str]
    preservedCategories: List[str]
    rationale: str
    estimatedExecutionTimeReductionPct: float


# --- Traceability Assistance ---
class AITraceabilityProposal(BaseModel):
    proposalId: str = Field(default_factory=lambda: str(uuid.uuid4()))
    requirementId: str
    functionId: str
    testCaseId: Optional[str] = None
    confidenceScore: float
    rationale: str
    status: ProposalReviewStatus = ProposalReviewStatus.PROPOSED


# --- Environment Recommendations ---
class AIEnvironmentRecommendation(BaseModel):
    recommendedFlags: List[str]
    recommendedDefines: List[str]
    recommendedIncludeDirs: List[str]
    stubsNeeded: List[str]
    sanitizersRecommended: List[str]
    rationale: str


# --- General Unified Response Container ---
class AIResponseDTO(BaseModel):
    suggestionId: str = Field(default_factory=lambda: str(uuid.uuid4()))
    modelUsed: str = "meta/llama-3.3-70b-instruct"
    isLiveCall: bool = False
    content: Any
    confidenceScore: Optional[float] = 0.95
    disclaimer: str = "DO-178C Notice: AI output is an advisory proposal and does not constitute authoritative verification evidence."
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
